[project]
name = "vibe-coding-toolkit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["jinja2>=3.1.6"]

[dependency-groups]
dev = ["ipython>=9.0.2"]
